# Use the official Node.js 16 Alpine image as a base
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source inside Docker image
COPY C:\Users\Tejovardhan\Downloads\hello-node\hello-node\Dockerfile

# Expose the port on which your app listens
EXPOSE 3000

# Command to run the application
CMD ["node", "main.js"]
